Comparing The Time between python list and numpy

In [2]:
#speed
#list
a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []
import time

start = time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time() - start)

2.4142353534698486


In [3]:
#numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time() - start)

0.20658349990844727


In [4]:
#Memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [7]:
a = np.arange(10000000, dtype=np.int16)
sys.getsizeof(a)

20000112

Advanced Indexing

In [12]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
#Fancy Indexing
#Here we are directly passing the index position to get the value
a[[0,2,3]]
a[[0,2,4,5]]
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [21]:
#Boolean Indexing
x = np.random.randint(1,100,24).reshape(6,4)
x

array([[83, 95, 53, 96],
       [92, 17,  9, 45],
       [50, 54, 22, 71],
       [42,  8, 19, 71],
       [13, 10,  6,  2],
       [53, 32, 88, 61]])

In [24]:
#Find all numbers greater than 50
x[x > 50]

array([83, 95, 53, 96, 92, 54, 71, 71, 53, 88, 61])

In [26]:
#Find out even numbers
x[x%2==0]

array([96, 92, 50, 54, 22, 42,  8, 10,  6,  2, 32, 88])

In [31]:
#Find all numbers greater than 50 and are even
x[(x > 50) & (x%2==0)]

array([96, 92, 54, 88])

In [35]:
#Find all numbers not divisible by 7
x[x%7!=0]
#or
x[~(x%7 == 0)]

array([83, 95, 53, 96, 92, 17,  9, 45, 50, 54, 22, 71,  8, 19, 71, 13, 10,
        6,  2, 53, 32, 88, 61])

BROADCATING

- The term broadcating describes how Numpy treats arrays with different shapes during arithmetic operation.

- The smaller array is 'broadcast' across the larger array so that they have compatible shapes.

In [38]:
#Same Shape
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

print(a + b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [41]:
# Different Shapes
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)

print(a + b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


BROADCATING RULES

1. Make the two arrays have the same number of dimensions.
* If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimensions.

2. Make each dimension of the two arrays the same size 
* If the size of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.

* If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcatsed, and an error is raised.


In [44]:
#More Examples
a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a + b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [47]:
#More Examples
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a + b)
#It will through an error as operands could not be broadcast together with shapes (3,4) (3,) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [51]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [53]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [55]:
a = np.array([1])
#shape -> (1,1)
b = np.arange(4).reshape(2,2)
#shape -> (2,2)

print(a)
print(b)

print(a + b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [57]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a + b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [58]:
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a + b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

Working With Mathematical Formulas

In [61]:
a = np.arange(10)
# np.sum(a)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [63]:
#sigmoid
a = np.arange(10)
def sigmoid(arr):
    return 1/(1 + np.exp(-(arr)))

sigmoid(a)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [67]:
#mean squared error
actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

def mse(actual, predicted):
    return np.mean((actual - predicted)**2)

mse(actual, predicted)

318.6

In [ ]:
#binary cross entropy

Working with Missing Values

In [68]:
#Working with missing values -> np.nan
a = np.array([1,2,3,4,np.nan,6])
a

array([ 1.,  2.,  3.,  4., nan,  6.])

In [69]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])

Plotting Graphs

In [71]:
#Plotting a 2D Plot
#x = y
 
import matplotlib.pyplot as plt

x = np.linspace(-10,10,100)
y = x
y


array([-10.        ,  -9.7979798 ,  -9.5959596 ,  -9.39393939,
        -9.19191919,  -8.98989899,  -8.78787879,  -8.58585859,
        -8.38383838,  -8.18181818,  -7.97979798,  -7.77777778,
        -7.57575758,  -7.37373737,  -7.17171717,  -6.96969697,
        -6.76767677,  -6.56565657,  -6.36363636,  -6.16161616,
        -5.95959596,  -5.75757576,  -5.55555556,  -5.35353535,
        -5.15151515,  -4.94949495,  -4.74747475,  -4.54545455,
        -4.34343434,  -4.14141414,  -3.93939394,  -3.73737374,
        -3.53535354,  -3.33333333,  -3.13131313,  -2.92929293,
        -2.72727273,  -2.52525253,  -2.32323232,  -2.12121212,
        -1.91919192,  -1.71717172,  -1.51515152,  -1.31313131,
        -1.11111111,  -0.90909091,  -0.70707071,  -0.50505051,
        -0.3030303 ,  -0.1010101 ,   0.1010101 ,   0.3030303 ,
         0.50505051,   0.70707071,   0.90909091,   1.11111111,
         1.31313131,   1.51515152,   1.71717172,   1.91919192,
         2.12121212,   2.32323232,   2.52525253,   2.72