CREATING NUMPY Arrays

In [2]:
#np.array
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#2D AND 3D array
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
#dtype
np.array([1,2,3], dtype=float)


array([1., 2., 3.])

In [12]:
#np.arange
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#with reshape
np.arange(1, 13).reshape(3,4)

#It will convert as a matrix format...what we pass

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
#np.random
np.random.random((3,4))

array([[0.31785785, 0.45529363, 0.16499025, 0.92642523],
       [0.7111086 , 0.6943853 , 0.9669255 , 0.31135182],
       [0.10234037, 0.49227228, 0.31017513, 0.13171394]])

In [27]:
#np.linspace
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [29]:
#np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
#ndim
a3.ndim

3

In [40]:
#shape
print(a2.shape)
print(a3.shape)
a3

(3, 4)
(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
#size
a2.size

12

In [47]:
#itemsize
a1.itemsize

4

In [48]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


Changing Datatype

In [53]:
# astype
#We are changing the data type 
# a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

Array Operations

In [55]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
#Scalar Operations
#Arithmetic Operation
a1 * 5      #We can do any kind of operation

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [75]:
#relational Operator
a2 > 20

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [76]:
#Vector Operation
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array Function

In [78]:
a1 = np.random.random((3, 3))
a1 = np.round(a1*100)
a1

array([[ 6., 47., 89.],
       [15., 58., 46.],
       [12., 66., 26.]])

In [86]:
#max/min/sum/prod
# np.max(a1)
# np.min(a1)
np.sum(a1)
# np.prod(a1)

365.0

In [90]:
#max/min/sum/prod Value for each row and column
#0 -> col
#1 -> row
# np.max(a1, axis=0)  #It will give maximum of each column
np.sum(a1, axis=1)    #It will give sum of each row  


array([142., 119., 104.])

In [91]:
#mean/median/std/var
np.mean(a1, axis=1)

array([47.33333333, 39.66666667, 34.66666667])

In [92]:
#trigonometric function
np.sin(a1)

array([[-0.2794155 ,  0.12357312,  0.86006941],
       [ 0.65028784,  0.99287265,  0.90178835],
       [-0.53657292, -0.02655115,  0.76255845]])

In [94]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2, a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [100]:
#log and exponent
# np.log(a1)
np.exp(a1)

array([[4.03428793e+02, 2.58131289e+20, 4.48961282e+38],
       [3.26901737e+06, 1.54553894e+25, 9.49611942e+19],
       [1.62754791e+05, 4.60718663e+28, 1.95729609e+11]])

In [107]:
#rounf/floor/ciel
# np.round(np.random.random((2,3))*100)
# np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[96., 12., 24.],
       [71., 93., 53.]])

Indexing And Slicing

In [113]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [114]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
a2[1,2]

6

In [119]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [122]:
# a3[1,0,1]     #-> for extracting 5
# a3[0,1,1]       #-> for extracting 3
a3[0,0,0]       #-> for extracting 0

0

In [123]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
# a1[2:5]
a1[2:5:2]

array([2, 4])

In [127]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
# a2[0,:]
a2[:,2]

array([ 2,  6, 10])

In [131]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [132]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [133]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [139]:
a2[1,::3]

array([4, 7])

In [142]:
a2[0:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [145]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [146]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [151]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [152]:
a3[0,1,:]

array([3, 4, 5])

In [153]:
a3[1,:,1]

array([10, 13, 16])

In [154]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [155]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

Iterating

In [158]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [164]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [165]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [166]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [168]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [169]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
#reshape

In [172]:
#Transpose
#It will convert row to column and column to row...Ex-(3,4) --> (4,3)
np.transpose(a2)
#or
# a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [174]:
#ravel
#It will convert the array into 1D Array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Stacking

In [178]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5
#In Stacking The shape should be same

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [181]:
#Horizontal Stacking
#It will concat two matrix horizonally
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [183]:
#Vertical Stacking
#It will concat two matrix Vertically
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Spliting

In [186]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
#Horizontal Splitting
#It should be Equal Division...We can not give Odd Number
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [196]:
#Vertical Splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]